export const LINKEDIN_LOCATIONS: string[] = [
  "Remote",
  "Hybrid",
  "On-site",
  "Istanbul, Turkey",
  "Ankara, Turkey",
  "Izmir, Turkey",
  "Bursa, Turkey",
  "Antalya, Turkey",
  "Kocaeli, Turkey",
  "Konya, Turkey",
  "Adana, Turkey",
  "Gaziantep, Turkey",
  "Mersin, Turkey",
  "Kayseri, Turkey",
  "Eskisehir, Turkey",
  "Samsun, Turkey",
  "Trabzon, Turkey",
  "Sanliurfa, Turkey",
  "Diyarbakir, Turkey",
  "Hatay, Turkey",
  "London, United Kingdom",
  "Manchester, United Kingdom",
  "Birmingham, United Kingdom",
  "Leeds, United Kingdom",
  "Bristol, United Kingdom",
  "Edinburgh, United Kingdom",
  "Glasgow, United Kingdom",
  "Dublin, Ireland",
  "Cork, Ireland",
  "Galway, Ireland",
  "Berlin, Germany",
  "Munich, Germany",
  "Hamburg, Germany",
  "Frankfurt, Germany",
  "Cologne, Germany",
  "Stuttgart, Germany",
  "Dusseldorf, Germany",
  "Leipzig, Germany",
  "Dortmund, Germany",
  "Amsterdam, Netherlands",
  "Rotterdam, Netherlands",
  "The Hague, Netherlands",
  "Utrecht, Netherlands",
  "Eindhoven, Netherlands",
  "Paris, France",
  "Lyon, France",
  "Marseille, France",
  "Toulouse, France",
  "Lille, France",
  "Nantes, France",
  "Nice, France",
  "Bordeaux, France",
  "Brussels, Belgium",
  "Antwerp, Belgium",
  "Ghent, Belgium",
  "Zurich, Switzerland",
  "Geneva, Switzerland",
  "Basel, Switzerland",
  "Bern, Switzerland",
  "Lausanne, Switzerland",
  "Vienna, Austria",
  "Graz, Austria",
  "Linz, Austria",
  "Salzburg, Austria",
  "Stockholm, Sweden",
  "Gothenburg, Sweden",
  "Malmo, Sweden",
  "Uppsala, Sweden",
  "Oslo, Norway",
  "Bergen, Norway",
  "Trondheim, Norway",
  "Stavanger, Norway",
  "Copenhagen, Denmark",
  "Aarhus, Denmark",
  "Odense, Denmark",
  "Helsinki, Finland",
  "Espoo, Finland",
  "Tampere, Finland",
  "Turku, Finland",
  "Warsaw, Poland",
  "Krakow, Poland",
  "Wroclaw, Poland",
  "Gdansk, Poland",
  "Poznan, Poland",
  "Lodz, Poland",
  "Prague, Czechia",
  "Brno, Czechia",
  "Ostrava, Czechia",
  "Budapest, Hungary",
  "Debrecen, Hungary",
  "Szeged, Hungary",
  "Bucharest, Romania",
  "Cluj-Napoca, Romania",
  "Timisoara, Romania",
  "Iasi, Romania",
  "Sofia, Bulgaria",
  "Plovdiv, Bulgaria",
  "Varna, Bulgaria",
  "Athens, Greece",
  "Thessaloniki, Greece",
  "Patras, Greece",
  "Lisbon, Portugal",
  "Porto, Portugal",
  "Braga, Portugal",
  "Madrid, Spain",
  "Barcelona, Spain",
  "Valencia, Spain",
  "Seville, Spain",
  "Malaga, Spain",
  "Bilbao, Spain",
  "Rome, Italy",
  "Milan, Italy",
  "Turin, Italy",
  "Bologna, Italy",
  "Naples, Italy",
  "Florence, Italy",
  "Venice, Italy",
  "Palermo, Italy",
  "Belgrade, Serbia",
  "Novi Sad, Serbia",
  "Zagreb, Croatia",
  "Split, Croatia",
  "Ljubljana, Slovenia",
  "Bratislava, Slovakia",
  "Kosice, Slovakia",
  "Vilnius, Lithuania",
  "Kaunas, Lithuania",
  "Riga, Latvia",
  "Tallinn, Estonia",
  "Reykjavik, Iceland",
  "Luxembourg, Luxembourg",
  "New York, United States",
  "San Francisco, United States",
  "Seattle, United States",
  "Los Angeles, United States",
  "San Diego, United States",
  "Austin, United States",
  "Boston, United States",
  "Chicago, United States",
  "Atlanta, United States",
  "Denver, United States",
  "Miami, United States",
  "Dallas, United States",
  "Houston, United States",
  "Phoenix, United States",
  "Portland, United States",
  "Washington, United States",
  "Philadelphia, United States",
  "Raleigh, United States",
  "Charlotte, United States",
  "Minneapolis, United States",
  "Toronto, Canada",
  "Vancouver, Canada",
  "Montreal, Canada",
  "Ottawa, Canada",
  "Calgary, Canada",
  "Edmonton, Canada",
  "Quebec City, Canada",
  "Waterloo, Canada",
  "Sao Paulo, Brazil",
  "Rio de Janeiro, Brazil",
  "Belo Horizonte, Brazil",
  "Curitiba, Brazil",
  "Porto Alegre, Brazil",
  "Brasilia, Brazil",
  "Mexico City, Mexico",
  "Guadalajara, Mexico",
  "Monterrey, Mexico",
  "Bogota, Colombia",
  "Medellin, Colombia",
  "Buenos Aires, Argentina",
  "Cordoba, Argentina",
  "Santiago, Chile",
  "Lima, Peru",
  "Quito, Ecuador",
  "Montevideo, Uruguay",
  "Dubai, United Arab Emirates",
  "Abu Dhabi, United Arab Emirates",
  "Riyadh, Saudi Arabia",
  "Jeddah, Saudi Arabia",
  "Doha, Qatar",
  "Muscat, Oman",
  "Kuwait City, Kuwait",
  "Manama, Bahrain",
  "Amman, Jordan",
  "Tel Aviv, Israel",
  "Jerusalem, Israel",
  "Cairo, Egypt",
  "Alexandria, Egypt",
  "Casablanca, Morocco",
  "Rabat, Morocco",
  "Tunis, Tunisia",
  "Lagos, Nigeria",
  "Abuja, Nigeria",
  "Nairobi, Kenya",
  "Cape Town, South Africa",
  "Johannesburg, South Africa",
  "Durban, South Africa",
  "Bangalore, India",
  "Hyderabad, India",
  "Pune, India",
  "Chennai, India",
  "Mumbai, India",
  "Delhi, India",
  "Gurugram, India",
  "Noida, India",
  "Kolkata, India",
  "Ahmedabad, India",
  "Jaipur, India",
  "Kochi, India",
  "Singapore, Singapore",
  "Kuala Lumpur, Malaysia",
  "Penang, Malaysia",
  "Jakarta, Indonesia",
  "Bandung, Indonesia",
  "Surabaya, Indonesia",
  "Bangkok, Thailand",
  "Chiang Mai, Thailand",
  "Manila, Philippines",
  "Cebu, Philippines",
  "Ho Chi Minh City, Vietnam",
  "Hanoi, Vietnam",
  "Da Nang, Vietnam",
  "Tokyo, Japan",
  "Osaka, Japan",
  "Yokohama, Japan",
  "Nagoya, Japan",
  "Fukuoka, Japan",
  "Kyoto, Japan",
  "Seoul, South Korea",
  "Busan, South Korea",
  "Incheon, South Korea",
  "Taipei, Taiwan",
  "Taichung, Taiwan",
  "Hong Kong, Hong Kong SAR",
  "Shenzhen, China",
  "Shanghai, China",
  "Beijing, China",
  "Guangzhou, China",
  "Chengdu, China",
  "Hangzhou, China",
  "Wuhan, China",
  "Xi'an, China",
  "Sydney, Australia",
  "Melbourne, Australia",
  "Brisbane, Australia",
  "Perth, Australia",
  "Adelaide, Australia",
  "Canberra, Australia",
  "Auckland, New Zealand",
  "Wellington, New Zealand",
  "Christchurch, New Zealand"
];
